language: java

sudo: false

addons:
  hosts:
  - db

services:
- docker

install:
- docker build -t database db/.
- docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
- mvn clean

jobs:
  include:
  - stage: unit tests
    install: skip
    jdk: oraclejdk11
    script: mvn test -Dtest=com.napier.sem.AppTest
  - stage: integration tests
    jdk: oraclejdk11
    script: mvn test -Dtest=com.napier.sem.AppIntegrationTest
  - stage: GitHub Release
      install: skip
      jdk: oraclejdk11
      script:
      - echo "Deploying to GitHub Releases"
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
      before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Kevin Chalmers"
      - git config --local user.email "k.chalmers@napier.ac.uk"
      # Create temporary tag from date and Git log.
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
      # Set tag
      - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        # Copy built JAR file.  JAR built in $TRAVIS_BUILD_DIR/
        file: $TRAVIS_BUILD_DIR/target/seMethods.jar
        skip_cleanup: true

stages:
- unit tests
- integration tests
- name: Github Release
  if: branch = master