version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is is db folder
  database:
    build: Database/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always